name: Run CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2']
        dependencies: ['normal', 'authoritative']

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
       coverage: none
       tools: composer, cs2pr

    - name: Install dependencies
      if: matrix.dependencies == 'normal'
      run: composer install --prefer-dist
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Install dependencies
      if: matrix.dependencies == 'authoritative'
      run: composer install --prefer-dist --classmap-authoritative
      env:
        COMPOSER_ROOT_VERSION: dev-master

    - name: Run Psalm
      if: matrix.php == '8.1'
      run: ./vendor/bin/psalm --threads=2 --output-format=github --shepherd

    - name: Run Phpunit
      run: ./vendor/bin/phpunit

    - name: Run PhpCs
      if: matrix.php == '8.1'
      run: ./vendor/bin/phpcs -q --report=checkstyle | cs2pr
